apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-discord
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager-discord
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-discord
    spec:
      containers:
        - name: alertmanager-discord
          image: benjojo/alertmanager-discord:latest
          env:
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: alertmanager-discord
                  key: webhook-url
          ports:
            - name: http
              containerPort: 9094
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager-discord
spec:
  selector:
    app.kubernetes.io/name: alertmanager-discord
  ports:
    - name: http
      port: 9094
      targetPort: http
